# Mailknight Main GitLab CI Pipeline
# Secure software supply chain automation system

include:
  - local: '.mailknight.yml'

variables:
  # Global variables for all projects
  FIPS_ENABLED: "true"
  TRIVY_VERSION: "0.48.3"
  SYFT_VERSION: "0.100.0"
  COSIGN_VERSION: "2.2.2"
  
  # Build hardening flags
  CFLAGS: "-fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIE"
  CXXFLAGS: "-fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIE"
  LDFLAGS: "-Wl,-z,relro,-z,now -pie"

stages:
  - validate
  - fetch-source
  - apply-patches
  - build
  - build-containers
  - scan
  - test
  - release

# Default rules for all jobs
default:
  image: registry.access.redhat.com/ubi8/ubi-minimal:latest
  before_script:
    - microdnf update -y
    - microdnf install -y git wget curl ca-certificates python3 tar python3-pyyaml findutils
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# Validate pipeline configuration
validate-pipeline:
  stage: validate
  script:
    - echo "Validating Mailknight pipeline configuration..."
    - scripts/validate-config.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

# Project-specific pipelines will be triggered based on changes
trigger-argocd:
  stage: validate
  trigger:
    include: projects/argocd/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - projects/argocd/**/*
        - patches/argocd/**/*
        - .mailknight.yml
        - scripts/**/*
  variables:
    PROJECT_NAME: "argocd"